 FROM python:3.6
 
 COPY requirements.txt /
 RUN pip install --upgrade pip
 RUN pip3 install -r /requirements.txt
 
 COPY ./src /home/src
 WORKDIR /home/src
 ENV PORT 8080 
 ENV PYTHONUNBUFFERED True
 
 CMD exec gunicorn --bind :$PORT --workers 3 --timeout 0 app:app